[package]
name = "flat-knn"
version = "0.1.0"
edition = "2021"

[dependencies]
simsimd = "6.4.9"
ordered-float = "4.2.0"
rand = "0.9.2"
rayon = "1.10.0"
ndarray = "0.16.0" 
faiss = "*"
linfa = "0.8.0"
linfa-nn = "0.8.0" 

[build]
rustflags = ["-C", "target-cpu=native"]
